export const words = {
  username: "میلاد الغوثی",
  karnameh: "کارنامه",
  karnamehDescription: "توضیحاتی درباره شرکت کارنامه",
  questionsList: "لیست سوالات",
  newQuestion: "سوال جدید",
  fakeName: "میلاد الغوثی",
  createNewQuestion: "ایجاد سوال جدید",
  subject: "موضوع",
  questionText: "متن سوال",
  createQuestion: "ایجاد سوال",
  cancel: "انصراف",
  time: "ساعت",
  date: "تاریخ",
  seeDetails: "مشاهده جزئیات",
  questionDetails: "جزئیات سوال",
  answers: "پاسخ‌ها",
  goodAnswer: "پاسخ خوب بود",
  badAnswer: "پاسخ خوب نبود",
  loading: "در حال بارگزاری ...",
  createQuestionDesciptionPlaceholder: "لطفا متن سوال خود را وارد کنید...",
  createQuestionTitlePlacholder: "لطفا عنوان سوال خود را وارد کنید...",
  submitYourAnswer: "پاسخ خود را ثبت کنید",
  writeYourAnswer: "پاسخ خود را بنویسید",
  answerText: "متن پاسخ ...",
  sendAnswer: "ارسال پاسخ",
  thisFieldIsRequired: "پر کردن این فیلد اجباریست",
  noData: "داده‌ای یافت نشد",
};
