export const words = {
  karnameh: "کارنامه",
  karnamehDescription: "توضیحاتی درباره شرکت کارنامه",
  questionsList: "لیست سوالات",
  newQuestion: "سوال جدید",
  fakeName: "میلاد الغوثی",
  createNewQuestion: "ایجاد سوال جدید",
  subject: "موضوع",
  questionText: "متن سوال",
  createQuestion: "ایجاد سوال",
  cancel: "انصراف",
  time: "ساعت",
  date: "تاریخ",
  seeDetails: "مشاهده جزئیات",
  questionDetails: "جزئیات سوال",
  answers: "پاسخ‌ها",
  goodAnswer: "پاسخ خوب بود",
  badAnswer: "پاسخ خوب نبود",
};
